language: python
branches:
  only:
   - master
install:
   - pip install pelican==3.5.0 ghp-import markdown
script:
   - make publish github
env:
    global:
       secure: "G1kYz/KByAo8X6thoYz/tbFLqcbPAgituKXAL/KrR9toEGIawBRkaT0CobxkRYz7VY8vyf6TM9gEpJjX6sQ/Hgp3aMUuwqpizaS91gVg98JsAvB/PCFSkydZvSddqzadrov+tlX7Mq4YhVTX45Znp52wqNgRXouffqsAIKIWDKg="