language: python
branches:
  only:
   - master
install:
   - pip install pelican==3.5.0 ghp-import markdown
script:
   - make publish github
env:
    global:
         secure: "EMwR3NmJGnzOzXK/cao4qpTGk7nNzt3/4sRb/dBepVpv5ZujZ4NQYMBn+hLDd2I8ueUxmx7OHrYrLLDBQ86nTHQlUAofUYEA+MKOJLTXG66cw1oRrRb0vVTUX7k+ZUzE+0F57QLeRFNFxiRI8aBGUbZ/S3vi/jlbOyw77hgB0pE="